### ISSUE TITLE
Unable to unpack IIS setup ~2012

### ISSUE THREAD

**Issue by DJ-Glock** [hifi/iss_extract#1]
Hello Tony et all.
I know that this repo is most probably not maintained, but who knows, may be you'll have some time for this.

I'm trying to extract data from IIS installer, that was created in 2012-2014:
![image](https://user-images.githubusercontent.com/26511191/141261844-3744f7be-041a-4b0c-b13a-62e5e276735b.png)

I've tried your util no luck. It does not see anything. I also tried several others tools, but no luck. The only thing I got with uniExtractor is analysis made by TrID/32 - File Identifier v2.02 tool:
```
TrID/32 - File Identifier v2.02 - (C) 2003-06 By M.Pontello
Definitions found:  2641
Analyzing...

Collecting data from file: C:\VIDAInstall\VIDA_unpacked\Install\DVD\Vida_dvdheader\Vida\setup.exe
 74.7% (.EXE) InstallShield setup (43050/17/16)
 18.2% (.EXE) Win32 Executable Generic (10527/13/4)
  3.4% (.EXE) Generic Win/DOS Executable (2002/3)
  3.4% (.EXE) DOS Executable Generic (2000/1)
  0.0% (.CEL) Autodesk FLIC Image File (extensions: flc, fli, cel) (7/3)
```
I'll appreciate any advice.

Some background: I'm trying to install volvo vida service repairs software on windows 11 with m1 chip. And main installer refuses to continue because of unsupported operation check. I tried to cheat, but no luck. So I want to unpack iis setup to find how it checks OS version.
[Main.zip](https://github.com/hifi/iss_extract/files/7518873/Main.zip)

**Comment by hifi** [comment]
I'd say this utility only works on very old IIS archives so I doubt it could help you. I would try 7zip as well if you haven't.

**Comment by DJ-Glock** [comment]
Hm, I tried many things, but not 7zip. And it unpacked installer. Shame in me.
Thanks a lot!
